#!/usr/bin/env bash
set -eo pipefail # this can be harmful, see https://www.youtube.com/watch?v=4Jo3Ml53kvc
. bs/.common || {
	echo 'Please run this script from the project root directory' >&2;
	exit 1;
}
# depends on
declare -r pkg='node_modules/.bin/pkg' # https://github.com/vercel/pkg
declare -r cache='bs/.cache'
declare -r folder_output=${1:-dist}

help(){
	if ! isHelp "${@}"; then return 0; fi
	echoReadmeInfo
	echo '  …and'
	$pkg --help
	exit 0
}
targets(){
	local -r targets=(
		"node18-linux-x64"
		"node18-macos-x64"
		"node18-macos-arm64" # experimental
		"node18-win-x64"
	)
	local targets_comma=''
	for target in "${targets[@]}"; do
		if [[ "$targets_comma" == '' ]]; then
			targets_comma="$target"
		else
			targets_comma="$targets_comma,$target"
		fi
	done
	echo "$targets_comma"
}
main(){
	help "${@}"
	# https://github.com/vercel/pkg-fetch, add to git (for sure)?
	PKG_CACHE_PATH="$cache" \
		npx pkg . \
		--target "$(targets)" \
		--out-path "$folder_output" \
		--compress GZip
	ls "$folder_output"
}

main "${@}"
